/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DownloadBrowserView.java
 *
 * Created on Jun 3, 2011, 4:05:03 PM
 */

package penny.downloadmanager.view.test;

import ca.odell.glazedlists.BasicEventList;
import ca.odell.glazedlists.EventList;
import ca.odell.glazedlists.GlazedLists;
import ca.odell.glazedlists.ObservableElementList;
import penny.downloadmanager.model.DownloadData;
import penny.downloadmanager.util.RandomChanges;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author john
 */
public class DownloadFrame extends javax.swing.JFrame {

    private static RandomChanges randomChanges;

    private ObservableElementList<DownloadData> downloadList;
    private DownloadTableFormatCM downloadTableFormat;

    /** Creates new form DownloadBrowserView */
    public DownloadFrame(EventList<DownloadData> downloads) {
        downloadList = new ObservableElementList(downloads, GlazedLists.beanConnector(DownloadData.class));
        downloadTableFormat = new DownloadTableFormatCM();
        downloadList.addListEventListener(downloadTableFormat);
        load(downloadList);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        urlText = new javax.swing.JTextField();
        downloadPanel1 = new DownloadPanel(downloadList, downloadTableFormat);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                stopRandom(evt);
            }
        });

        urlText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout downloadPanel1Layout = new javax.swing.GroupLayout(downloadPanel1);
        downloadPanel1.setLayout(downloadPanel1Layout);
        downloadPanel1Layout.setHorizontalGroup(
            downloadPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );
        downloadPanel1Layout.setVerticalGroup(
            downloadPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(urlText, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(downloadPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(urlText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(downloadPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopRandom(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_stopRandom
        randomChanges.stop();
    }//GEN-LAST:event_stopRandom

    private void urlTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlTextActionPerformed
        try {
            downloadList.add(new DownloadData(new URL(urlText.getText())));
            urlText.setText("");
        } catch (MalformedURLException ex) {
            Logger.getLogger(DownloadFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_urlTextActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        final EventList downloads = GlazedLists.threadSafeList(new BasicEventList());
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DownloadFrame(downloads).setVisible(true);
            }
        });

        randomChanges = new RandomChanges(downloads);
        Thread t = new Thread(randomChanges);
        t.start();
    }

    public static void load(EventList downloads) {
        List<String> urls = new ArrayList<String>();
        urls.add("http://www.google.com/");
        urls.add("http://www.yahoo.com/");
        urls.add("http://www.facebook.com/");
        urls.add("http://www.tomshardware.com/");
        urls.add("http://www.gmail.com/");
        urls.add("http://www.msn.com/");
        urls.add("http://www.hotmail.com/");
        urls.add("http://www.issinc.com/");
        urls.add("http://www.youtube.com/");
        urls.add("http://www.netbeans.com/");

        for (String s : urls) {
            try {
                DownloadData d = new DownloadData(new URL(s));
                downloads.add(d);
            } catch (MalformedURLException ex) {
                Logger.getLogger(DownloadFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private penny.downloadmanager.view.test.DownloadPanel downloadPanel1;
    private javax.swing.JTextField urlText;
    // End of variables declaration//GEN-END:variables

}
